In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df = df[df['IMDb'] > 6.0]

In [5]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [9]:
df.to_csv("data_updated.csv", index = False)

In [10]:
df = pd.read_json("my.json")

In [11]:
df

   id     name                email  is_active
0   1    Alice    alice@example.com       True
1   2      Bob      bob@example.com      False
2   3  Charlie  charlie@example.com       True

In [14]:
data = [
  {
    "id": 1,
    "name": "Alice",
    "email": "alice@example.com",
    "is_active": True
  },
  {
    "id": 2,
    "name": "Bob",
    "email": "bob@example.com",
    "is_active": False
  },
  {
    "id": 3,
    "name": "Charlie",
    "email": "charlie@example.com",
    "is_active": True
  }
]

In [15]:
df

   id     name                email  is_active
0   1    Alice    alice@example.com       True
1   2      Bob      bob@example.com      False
2   3  Charlie  charlie@example.com       True

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         3 non-null      int64
 1   name       3 non-null      object
 2   email      3 non-null      object
 3   is_active  3 non-null      bool
dtypes: bool(1), int64(1), object(2)
memory usage: 207.0+ bytes